### ISSUE TITLE
ember-cli-head support again?

### ISSUE THREAD

**Issue by danieledraganti** [ember-cli/ember-page-title#201]
Hello everyone,
I recently upgraded this Addon from 5.x to 6.x, and noticed that it no longer needs `ember-cli-head` to work. I can understand why you went this way, but I believe it would be good to let the developer decide whether to inject the generated `title` in `head.hbs` (or the `head-data` model, anyway).
For example, in my case, I make extensive use of OpenGraph meta tags to give more context to the page; by not having the `title` property automatically filled in the `head-data` model, this would mean I have to pass the title somewhere else in my template, therefore duplicating code.
I am trying to retrieve this from your `page-title-list`'s `toString()` method, but this definitely involves extra work, and more custom code.

**Comment by raido** [comment]
Do I understand it correctly, that main issue is having to define *title* twice. Once for OpenGraph tags and once for `<title>` element?

Therefore to have single source of truth for title, you need to collect this data by various workarounds? 
Could you provide example https://ember-twiddle.com/ of your setup?

**Comment by danieledraganti** [comment]
> Do I understand it correctly, that main issue is having to define _title_ twice. Once for OpenGraph tags and once for `<title>` element?
> 
> Therefore to have single source of truth for title, you need to collect this data by various workarounds?
> Could you provide example https://ember-twiddle.com/ of your setup?

Sorry, I didn't have time yet to create a twiddle. I will just copy a quick snippet of the code I use, in `routes/application.js`, maybe it's enough for you guys to understand what my question is:
```js
import { inject as service } from '@ember/service';
import { storageFor } from 'ember-local-storage';
import Route from '@ember/routing/route';

export default class ApplicationRoute extends Route {
  @service intl;
  @service headData;
  @service('best-language') bestLanguage;
  @service('page-title-list') pageTitle;

  beforeModel() {
    const locale = this.bestLanguage.bestLanguageOrFirst(this.intl.locales).language;
    this.headData.title = this.pageTitle.toString();
    this.headData.locale = locale;
    this.headData.locales = this.intl.locales;
    return this.intl.setLocale(locale);
  }
}
```
Now, `this.pageTitle.toString()` does not seem to work to retrieve current title. Maybe an idea would be to create a computed property in the `page-title-list` service that will always retrieve the title based on the setup of the current route? So that it can then be passed to other meta tags via the `headData` service.

Thank you in the meanwhile.

**Comment by raido** [comment]
`toString()` method is not observable like this.

We have few options here, some more optimal than others:

* Expose some event via Ember.Evented

```
@service
pageTitle;

init() {
 ...
 this.pageTitle.on('titleDidUpdate', () => { }); // similar to RouterService routeDidChange
}
```

* Add component and register for update via template context:

```
<PageTitle ... as @onTitleDidUpdate=.../>

// OR 

<PageTitle ... as |state|>
   // push to other things -> 
  // state.currentTitle
</PageTitle>
```

* Last more of a **workaround**, than solution:

Use MutationObserver to observe `<title>` element update and read value from DOM. This can viable until better support for getting current title via ember-page-title services ships.

--

From those 3 options, I would prefer `titleDidUpdate` approach - as it is advanced usage specifically for integration like with `ember-cli-head` and therefore not forcing heavier component based syntax via templates for existing consumers.

cc @knownasilya for brainstorming.

**Comment by danieledraganti** [comment]
Totally agree on the `titleDidUpdate` event. It would make the computed title available practically anywhere.
Would that also work with Fastboot though? I can see you already have a workaround in your service to handle Fastboot, the event should be triggered accordingly, so that it doesn't happen after its page rendering.

**Comment by raido** [comment]
> Totally agree on the `titleDidUpdate` event. It would make the computed title available practically anywhere.
> Would that also work with Fastboot though? I can see you already have a workaround in your service to handle Fastboot, the event should be triggered accordingly, so that it doesn't happen after its page rendering.

That is more of technical implementation detail, but yes it would work for both. Title updating is still scheduled via runloop "afterRender" queue, just the "output destination" of the title for DOM is different.

For this particular event case, triggering would be in the end of title updating method logic.

**Comment by knownasilya** [comment]
I'm also fine with an event. A bit concerned about longevity of `Ember.Evented` and using mixins in general. cc @rwjblue

**Comment by danieledraganti** [comment]
Added a pull request using the same method on current RouterService in core Ember, which reopens the class at the end. Seems to be working fine; let me know what you guys think.
@knownasilya Agree it's not the best long-term solution; I guess the alternative would be to re-write the code by using getters and setters on a tracked `pageTitle` property, but I guess that'd need a deeper re-write of the code.

**Comment by rwjblue** [comment]
> I'm also fine with an event. A bit concerned about longevity of Ember.Evented and using mixins in general. cc @rwjblue

Agree. I think I'd prefer to let folks have a hook that we call instead of the event itself. That way you could extend from our service and implement the specific method we call, instead of `super`ing you would do "your own thing".

**Comment by raido** [comment]
Hook is better for long term.

However current page-title-list service is not meant for public access.

We need to re-export or rename all together it as "page-title". (Possibly breaking change, requiring v7 release?).

We need to mark all methods private besides the hook.

**Comment by raido** [comment]
Renaming will be definitely a breaking change, based on Github code search.

https://github.com/search?q=%22page-title-list%22&type=code

*(v6 broke things like "defaultSeparator" although it was meant to be configured via config/environment.js)*

**Comment by raido** [comment]
Coming back to components. It narrows down flexibility but for ember-cli-head integration it would work.

We could have provider component, example:

```
// head.hbs
<PageTitleProvider as |provider|>
     ..og tags, other meta tags for ember-cli-head head
     <meta og:title={{provider.title}} />
</PageTitleProvider>
```

This feels a bit *more natural* on some levels *but* this means having internal state as `@tracked` (which I'd prefer not to, due to leaking state and tight coupling risks) or private hooks for data provider component to hook into. In v6 we un-tangled `service:page-title-list` internal state from any reactivity contexts.

**Comment by raido** [comment]
With data provider pattern, we would need only single new tracked property, let's call it "currentTitle" - which would set instead of https://github.com/ember-cli/ember-page-title/pull/202/files#diff-ca58e4ea1d078915605a3eee66bfcfa9875e2e047ce0c536effb419f72d53da2R223 - event here.

And then PageTitleDataProvider component could simply yield it.

--

But this is still limited solution compared to hook/event.

Imagine you have:

```
router.on('routeDidChange', () => {
  // track page view with third party tools, that collect "document.title"
});
 ```

Today I don't think we have guarantee that at the time of "routeDidChange" event actually `document.title` is at it's latest value, because title itself is update in "afterRender" queue which often probably means updating title after "routeDidChange" event. Therefore you cannot observe document.title directly or rely on third party tools being able to do so.

**Comment by bertdeblock** [comment]
A hook that gets called with the new title value seems like a good starting point to me 👍.

**Comment by knownasilya** [comment]
@bertdeblock if you have free cycles, this would be an easy feature to PR. I closed the event PR we had https://github.com/ember-cli/ember-page-title/pull/202#issuecomment-758923682 but that would be a good reference.

**Comment by bertdeblock** [comment]
Sure, I can have a look, but what to do about the fact that the service currently isn't considered public API?
Do I take this into account? Should that be a different PR? ...

**Comment by raido** [comment]
If we go down the hook path, we can have 2 layer services. 

We add 'page-title' service as new public service + new hook. 

Internally this service actually hooks into private hook in 'page-title-list' service. 

This way we don't need major version bump + get base service for future public methods/props.

**Comment by danieledraganti** [comment]
> If we go down the hook path, we can have 2 layer services.
> 
> We add 'page-title' service as new public service + new hook.
> 
> Internally this service actually hooks into private hook in 'page-title-list' service.
> 
> This way we don't need major version bump + get base service for future public methods/props.

I like this solution. We'd also have a `page-title` service ready should any other functionality be implemented in the future.

**Comment by raido** [comment]
Exactly. Eventually we can slowly move towards new service being the only service if required. Although I would not rush it. 

Ember.js v3.24 just included v6 of this addon in its blueprint and having major bump for this addon quickly after might not be recieved well.

**Comment by bertdeblock** [comment]
If the idea is to have only one service in the future (which I would prefer). We could rename the service internally to `page-title`, _but_ have it exported as `page-title` _and_ `page-list-service`. That way we can keep the changes in one location (the `page-title` service) and we can also work on making everything else properly private. Deprecating the `page-list-service` in the future would be a deprecation warning away in the constructor I think?

**Comment by raido** [comment]
I get your intention but we don't know if folks have imported directly from addon path itself and re-exporting themselves for overrides etc. 

Unlikely but it is a possibility. To start with safest route, I'd add new public service as mentioned above to get hook itself shipped and keep scope just on the hook and later we can figure out the least disruptive way to replace internals.

**Comment by bertdeblock** [comment]
You could keep the export in the `addon` folder as well of course if that's a concern. I just wanted to avoid spreading code over multiple services to achieve a new feature.

**Comment by raido** [comment]
Yes, that's a nice solution, keeping old addon path as simple re-export. 👍

**Comment by raido** [comment]
Hold, we cannot re-export same base service class as 'page-title-list' and 'page-title', because each of them will be separate instance. This breaks one of the services, because helper we have injects the service to push title tokens to internal array. 

That's why I proposed 2 layers of services and internal private hook + public hook solution.

**Comment by bertdeblock** [comment]
Ah yes, that could indeed cause issues. Good to know!

**Comment by bertdeblock** [comment]
Already made a [draft PR](https://github.com/ember-cli/ember-page-title/pull/207) to check if this direction is okay.

**Comment by raido** [comment]
Integration with `ember-cli-head` can be done with v6.1.0 like this:

```
// app/services/page-title.js

import EmberPageTitleService from 'ember-page-title/services/page-title';

export default class PageTitleService extends EmberPageTitleService {
  @service headData;

  titleDidUpdate(title) {
    this.headData.ogTitle = title;
  }
}
```

**Comment by kceb** [comment]
So I'm currently facing something like @raido described [here](https://github.com/ember-cli/ember-page-title/issues/201#issuecomment-724636040)

I essentially have the following
```
router.on('routeDidChange', () => {
  thirdPartyService.log(document.title)
});
```

As expected, the document.title is a stale value as the title is updated `afterRender`. Any idea on a possible workaround/solution to obtain the page title on `routeDidChange`?

**Comment by knownasilya** [comment]
You should be able to inject the page title service into the router.

**Comment by bertdeblock** [comment]
Don't think there is any need to use the router service for this. You can override the `titleDidUpdate` hook on the `page-title` service as mentioned [here](https://github.com/ember-cli/ember-page-title#page-title-service) and inject your `third-party` service. Something like this:

```js
// app/services/page-title.js

import { inject as service } from '@ember/service';
import EmberPageTitleService from 'ember-page-title/services/page-title';

export default class PageTitleService extends EmberPageTitleService {
  @service('third-party') thirdPartyService

  titleDidUpdate(title) {
    this.thirdPartyService.log(title);
  }
}
```
