### ISSUE TITLE
Use `willDestroy` in helper?

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-page-title#210]
More of a general wonderment that popped up when navigating the codebase.
Is there a reason `destroy` is used instead of the `willDestroy` hook in the `page-title` helper?
`destroy` also contains [some logic](https://github.com/emberjs/ember.js/blob/v3.24.0/packages/%40ember/-internals/runtime/lib/system/core_object.js#L524) that isn't executed now.

**Comment by raido** [comment]
I am not sure there is any particular reason. This code is from about 6 years ago. 

Good catch regardless and I've opened PR to address this.

**Comment by knownasilya** [comment]
v6.2.1 has this
