### ISSUE TITLE
Feature Request: Support for dynamic page title notifications.

### ISSUE THREAD

**Issue by burritoIand** [ember-cli/ember-page-title#215]
Working on a site with a requirement to flash a title notification update when the app tab is unfocused and I thought I'd post here to see if anyone thinks that'd possibly be a good fit for this library?

e.g. "2 messages" -> "normal title" -> "2 messages"...etc

I was thinking basically we could extend the page title service with an optional api to pass in a list of notification messages, which if present, will be flashed in the title bar on a schedule as the tab is unfocused.

To me it feels like a good fit to bake into this as this library is already handling the page title.

Let me know what you think! In any case I'm going to build something in my current project and can share when it's ready.

**Comment by knownasilya** [comment]
Seems like a dynamic title:

```hbs
{{page-title this.title}}
```

Would handle this use case where the `title` is a getter that brings in those messages and generates an alt title if messages exist. Have you tried this approach?

**Comment by burritoIand** [comment]
hey @knownasilya, ok yeah wondering if I'm overthinking it? I was thinking something similar except that we'd add the optional machinery to handle the dynamic updates into this library?

for instance what if it accepted an array, and if the title was passed in as an array, it would just automatically cycle between them on a set/configurable interval?
```
{{page-title this.titleSet}}

titleSet = [<titleA>, <titleB>]
```
I guess I can just handle it in the app too though :D

**Comment by knownasilya** [comment]
It already works like so 

```hbs
{{page-title this.messageCount this.title}}
```

See https://github.com/ember-cli/ember-page-title/blob/master/addon/helpers/page-title.js#L28

**Comment by raido** [comment]
Check out this twiddle - https://ember-twiddle.com/40aaddaa95d00836a6c922ccdf1929f2?openFiles=templates.application%5C.hbs%2C

**Comment by burritoIand** [comment]
@knownasilya @raido I see, thank you!
