### ISSUE TITLE
Remove IE 11 support code

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-page-title#243]
https://github.com/ember-cli/ember-page-title/blob/master/addon/src/services/page-title.js#L241-L253

We can also remove `ie 11` from `targets.js` in the `docs` and `test-app` apps.

**Comment by knownasilya** [comment]
https://github.com/ember-cli/ember-page-title/blob/master/addon/src/services/page-title.js#L241-L253

**Comment by bertdeblock** [comment]
Though as long as this addon officially supports 3.28, we can't do this I think?
